FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN sed -i 's/export default config;/config.viteFinal = (c) => { c.base = "\/storybook\/"; return c; };\nexport default config;/' .storybook/main.ts
RUN npx storybook build

FROM nginx:alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/storybook-static /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
